### ISSUE TITLE
Decouple javascript code from locale data?

### ISSUE THREAD

**Issue by rxaviers** [twitter/twitter-cldr-js#20]
Hey guys,

This is a question, not an issue. So, forgive me if I should have used another channel for that.

You currently embed CLDR data into your javascript via this.tokens variables.

Have you considered decoupling it, and have JSON CLDR data loaded by the javascript instead? It would help you to reduce re-work (rebuild) maintenance, and also would give users more flexibility (avoiding stuff like #11).

**Comment by camertron** [comment]
This has hit master thanks to @radzinzki.
