### ISSUE TITLE
Russian pluralisation rules are out of sync with other resources

### ISSUE THREAD

**Issue by KL-7** [twitter/twitter-cldr-js#54]
The following code works in other locales, but fails in Russian:

``` javascript
alert((new TwitterCldr.TimespanFormatter()).format(3));
```

According to the [pluralization rules](https://github.com/twitter/twitter-cldr-js/blob/master/lib/assets/javascripts/twitter_cldr/ru.js#L153) `few` category should be used for number `3`, but there's no [formatting patterns](https://github.com/twitter/twitter-cldr-js/blob/master/lib/assets/javascripts/twitter_cldr/ru.js#L177) for this category.

It might have something to do with the fact that at some point `few` category was [mistakenly removed](http://cldr.unicode.org/index/downloads/cldr-25#TOC-Changes-to-plural-ordinal-rules) from Russian pluralization rules in CLDR. It should be put back both into pluralization rules and into other resources (e.g., time formatting patterns).

**Comment by mathewbgordon** [comment]
It looks like this may still be an issue; using the updated version of the ```twitter_cldr_js``` gem - v2.3.2, we're still seeing the same error with certain pluralization forms in Russian, for example in the console:
```new TwitterCldr.TimespanFormatter().format(-119)```
gives
```Uncaught TypeError: Cannot read property 'replace' of undefined```
while
```new TwitterCldr.TimespanFormatter().format(-21)```
(as well as others) works fine:
```"21 секунду назад"```

**Comment by KL-7** [comment]
@mathewbgordon v2.3.2 was released in September, well before the issue was fixed. I guess we should release a new version. Meanwhile, you can try using `ru.js` from master. I just tested it and for

```
new TwitterCldr.TimespanFormatter().format(-119)
```

it returns `2 минуты назад` that is what I'd expect it to return.

**Comment by KL-7** [comment]
@mathewbgordon I just pushed v2.4.0 to rubygems, give it a try. It contains quite a few resources changes (we upgraded to CLDR v26) and several fixes including the one for this issue.

**Comment by camertron** [comment]
Yikes I thought I had published this a long time ago. Totally my bad.

**Comment by mathewbgordon** [comment]
@KL-7  seems good so far - thanks!
