### ISSUE TITLE
Unwanted leading commas in Hindi DecimalFormatter

### ISSUE THREAD

**Issue by mrubens** [twitter/twitter-cldr-js#64]
Hi, I'm trying to use the DecimalFormatter in Hindi and ending up with what I think are unwanted leading commas in some cases. Is this a bug? Thanks!

`new TwitterCldr.DecimalFormatter().format(1) => ",1" (incorrect)`
`new TwitterCldr.DecimalFormatter().format(10) => ",,10" (incorrect)`
`new TwitterCldr.DecimalFormatter().format(100) => ",,100" (incorrect)`
`new TwitterCldr.DecimalFormatter().format(1000) => "1,000" (correct)`

**Comment by KL-7** [comment]
Hey @mrubens, sorry for a late response and thanks for reporting the issue. It's definitely a bug, I'll take a look.

**Comment by KL-7** [comment]
Should be fixed in master now, let me know if you still experience any issues with it. I'll push a new version to npmjs early next week.

**Comment by montanamendy** [comment]
Yeah still exp problems, no worries though. Will get new version when pushed to npm

**Comment by KL-7** [comment]
I believe the fix has been pushed to npm.js in August. Let me know if the latest version there is still broken.
