### ISSUE TITLE
bidi_class_for is a large bottleneck

### ISSUE THREAD

**Issue by edkimmel** [twitter/twitter-cldr-js#67]
I integrated the node module of this into a project of mine. I immediately noticed that the bidi_class_for function was a huge bottleneck to my text rendering.

I looked further into the javascript to see what it's doing, and I believe the linear search / parseInt are to blame.  I don't know enough about ruby or your build system that generates the javascript, but I can provide an alternative to the final javascript result which performs much faster.

I flatted the bidi class ranges into an array and sorted the ranges by the min value. This allowed me to do a binary search to find the bidi class instead of a linear lookup. It can be improved further by implementing an interpolation search instead of binary.

Here's a pastebin of the changes I made. I figured a pull request wouldn't help, since I only changed what appears to be a generated file. If you'd like to see a pull request, let me know. http://pastebin.com/yEwHkmhf

**Comment by camertron** [comment]
Is it just me or was there a description here before? What happened to the pastebin link? @edkimmel

**Comment by KL-7** [comment]
@camertron I believe it was moved to #68
