### ISSUE TITLE
Russian date formats do not parse out "real character" escaping single quotes, redux

### ISSUE THREAD

**Issue by pchew-change** [twitter/twitter-cldr-js#75]
c.f. https://github.com/twitter/twitter-cldr-js/issues/57

@KL-7 - it looks like the single-quotes around the г for "года" have returned.

![single_quotes](https://cloud.githubusercontent.com/assets/1437602/15551206/d22c55a6-2269-11e6-8ab8-4ea2a072a68f.png)

**Comment by KL-7** [comment]
Hey, thanks for flagging this. What version of the library are you using?

**Comment by pchew-change** [comment]
Hi there!
It looks like we are currently running 1.3.1, but will be running 1.3.6 after some infrastructure upgrades.
I can't imagine that we had reverted to a version earlier than the fix in the previous ticket from 1.5 years ago, though.

**Comment by KL-7** [comment]
I think that's exactly what happened. Version [1.3.1](https://github.com/twitter/twitter-cldr-npm/commits/v1.3.1) was released in April 2014 and the [fix for this issue](https://github.com/twitter/twitter-cldr-js/pull/58) was merged in November that year.

**Comment by pchew-change** [comment]
Thanks.
I'm discussing with my engineers now.
cheers!

**Comment by montanamendy** [comment]
Thanks @pchew-change
