### ISSUE TITLE
LongDecimalFormatter uses wrong word when rounding up

### ISSUE THREAD

**Issue by lionel-rowe** [twitter/twitter-cldr-js#91]
**Describe the bug**

`LongDecimalFormatter` uses the wrong word when rounding up. For example, there's no "1000 thousand" in English or "10千" in Chinese:

```
999 thousand, 1000 thousand, 1 million
9千, 10千, 1万
```

**To Reproduce**

```js
console.log([
	['en', 999_499, 999_500, 1_000_000],
	['zh-cn', 9_499, 9_500, 10_000],
].map(([locale, ...ns]) => {
	const TwitterCldr = require('twitter_cldr').load(locale)

	return ns.map((n) => {
		return new TwitterCldr.LongDecimalFormatter().format(n)
	}).join(', ')
}).join('\n'))
```

**Expected behavior**

Output for 999,500 in `en` should be "1 million". Output for 9,500 in `zh-cn` should be "1万".

**Environment**

twitter_cldr 2.2.0, Node v16.13.0

**Comment by camertron** [comment]
Hey @lionel-rowe, thanks for reporting this. My time is very limited these days, are you able to dive in and contribute a fix?

**Comment by lionel-rowe** [comment]
> Hey @lionel-rowe, thanks for reporting this. My time is very limited these days, are you able to dive in and contribute a fix?

Can't promise anything, but I'll have a look into it if I get a chance.
